TourismWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 主页面路由
    path('index/', include('index.urls')),
    # 用户登录注册路由
    path('userprofile/', include('userprofile.urls')),
    # 用户重置密码路由
    path('password-reset/', include('password_reset.urls')),
    # 论坛路由
    path('article/', include('article.urls')),
    # 商城路由
    path('equipMall/', include('equipMall.urls')),
    # 酒店推荐路由
    path("hotel/", include('hotel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # 添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from . import views
from django.urls import path
app_name = 'hotel'

urlpatterns = [
    # 目前还没有urls
]

urlpatterns = [
    # path函数将url映射到视图
    path('hotel-list/', views.hotel_list, name='hotel_list'),
    # 酒店详情
    path('hotel-detail/<int:id>/', views.hotel_detail, name='hotel_detail'),
]

hotel/models.py
from django.db import models
# 导入内建的User模型。
# from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
# from django.utils import timezone
# Django-taggit
# from taggit.managers import TaggableManager


class Hotel(models.Model):
    # 酒店标题图
    avatar = models.TextField()
    # 酒店名称
    name = models.TextField()
    # 酒店评分
    score = models.TextField()
    # 酒店信息。
    msg = models.TextField()
    # 酒店标签
    # tags = TaggableManager(blank=True)
    # 酒店价格
    price = models.FloatField()
    # 新增酒店地址
    addr = models.TextField()
    # detail网址
    href = models.TextField()

hotel/views.py
from django.shortcuts import render, redirect
# Create your views here.
from django.db.models import Q
# 导入数据模型ArticlePost
from .models import Hotel
# 引入分页模块
from django.core.paginator import Paginator
from static.spider import quanerCrawl


def getWebHotel():
    # address = ['beijing_city']
    address = ['beijing_city', 'shanghai_city', 'guangzhou', 'chengdu']
    for addr in address:
        hotel_item = quanerCrawl.getCity(addr).getDetail()
        i = 0
        while i < len(hotel_item[0]):
            # print(hotel_item[2][i])
            if Hotel.objects.filter(name=hotel_item[1][i]):
                continue
            new_hotel = Hotel(
                avatar=hotel_item[0][i],
                name=hotel_item[1][i],
                score=hotel_item[2][i],
                msg=hotel_item[4][i],
                # tags=addr,
                price=hotel_item[3][i],
                addr=addr,
                href=hotel_item[5][i]
            )
            new_hotel.save()
            i = i + 1


def hotel_list(request):
    # getWebHotel()
    hotel_list = Hotel.objects.all()
    addr = request.GET.get('addr')
    search = request.GET.get('search')
    # 用户搜索逻辑
    if search:
        # 用 Q对象 进行联合搜索
        hotel_list = Hotel.objects.filter(
            Q(name__icontains=search) | Q(msg__icontains=search)
        )
    else:
        # 将 search 参数重置为空
        search = ''
    if addr == 'shanghai_city':
        hotel_list = Hotel.objects.filter(Q(addr__icontains=addr))
    elif addr == 'guangzhou':
        hotel_list = Hotel.objects.filter(Q(addr__icontains=addr))
    elif addr == 'beijing_city':
        hotel_list = Hotel.objects.filter(Q(addr__icontains=addr))
    elif addr == 'chengdu':
        hotel_list = Hotel.objects.filter(Q(addr__icontains=addr))
    paginator = Paginator(hotel_list, 9)
    page = request.GET.get('page')
    hotels = paginator.get_page(page)
    # 增加 search 到 context
    print(hotel_list[0].avatar)
    context = {'hotels': hotels, 'search': search, 'addr': addr}
    return render(request, 'hotel/list.html', context)


def hotel_detail(request, id):
    # 取出对应的酒店
    hotel = Hotel.objects.get(id=id)
    # 重定向到hotel.href
    return redirect(hotel.href)

templates/hotel/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% block content %}
<!-- 定义放置酒店的div容器 -->
<div class="container">
    <br>
    <div class="container">
        <nav aria-label="breadcrumb">
            <label style="font-size: 22px ; color: black;">酒店推荐 &nbsp; &nbsp; </label></li>
            <a href="{% url 'hotel:hotel_list' %}" style="font-size: 22px">
                全部酒店&nbsp; &nbsp;
            </a>
            <a href="{% url 'hotel:hotel_list' %}?addr=beijing_city" style="font-size: 22px">
                北京&nbsp; &nbsp;
            </a>
            <a href="{% url 'hotel:hotel_list' %}?addr=shanghai_city" style="font-size: 22px">
                上海&nbsp; &nbsp;
            </a>
            <a href="{% url 'hotel:hotel_list' %}?addr=guangzhou" style="font-size: 22px">
                广州&nbsp; &nbsp;
            </a>
            <a href="{% url 'hotel:hotel_list' %}?addr=chengdu" style="font-size: 22px">
                成都&nbsp; &nbsp;
            </a>
            <a href="#" style="font-size: 22px">
                其他&nbsp; &nbsp;
            </a>
        </nav>
    </div>
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline">
                <label class="sr-only">content</label>
                <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索酒店..." required>
            </form>
        </div>
    </div>
    <div class="row mt-2">
        {% for hotel in hotels %}
        <div class="col-4 mb-4">
            <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 名字 -->
                <!-- 标题图 -->
                {% if hotel.avatar %}
                <img src="{{ MEDIA_URL }}/media/{{ hotel.avatar }}" alt="avatar" class="card-img-top">
                {% endif %}
                <div class="card-body">
                    <div class="card-text">{{ hotel.name }}</div>
                    <div class="card-text">
                        <p class="card-text" style="color: blue">{{ hotel.score }}分</p>
                    </div>
                    <div class="card-text">{{ hotel.msg }}</div>
                    <div class="card-text">
                        <span>
                            {% for tag in hotel.tags.all %}
                            <a href="#" class="badge badge-success">
                                {{ tag }}
                            </a>
                            {% endfor %}
                        </span>
                        <label class="card-text" style="color: red">
                            ￥{{ hotel.price}}起
                        </label>
                    </div>
                </div>
                <!-- 注脚 -->
                <div class="card-footer text-center">
                    <a href="{{ hotel.href }}" class="btn btn-primary">了解详情</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if hotels.has_previous %}
                <a href="?page=1&addr={{ addr }}" class="btn btn-success">&laquo; 1</a>
                <span>...</span>
                <a href="?page={{ hotels.previous_page_number }}&addr={{ addr }}" class="btn btn-secondary">...</a>
                {% endif %}
                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ hotels.number }}
                </span>
                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if hotels.has_next %}
                <a href="?page={{ hotels.next_page_number }}&addr={{ addr }}" class="btn btn-secondary">{{ hotels.next_page_number }}</a>
                <span>...</span>
                <a href="?page={{ hotels.paginator.num_pages }}&addr={{ addr }}" class="btn btn-success">{{ hotels.paginator.num_pages }} &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock content %}