TourismWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 主页面路由
    path('index/', include('index.urls')),
    # 用户登录注册路由
    path('userprofile/', include('userprofile.urls')),
    # 用户重置密码路由
    path('password-reset/', include('password_reset.urls')),
    # 论坛路由
    path('article/', include('article.urls')),
    # 商城路由
    path('equipMall/', include('equipMall.urls')),
    # 酒店推荐路由
    path("hotel/", include('hotel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # 添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from . import views
from django.urls import path
app_name = 'hotel'

urlpatterns = [
    # 目前还没有urls
]

urlpatterns = [
    # path函数将url映射到视图
    path('hotel-list/', views.hotel_list, name='hotel_list'),
    # 酒店详情
    path('hotel-detail/<int:id>/', views.hotel_detail, name='hotel_detail'),
]

userprofile/urls.py
# -*- coding: utf-8 -*-
# @Author: 100yang
# @Date:   2020-04-17
# @Last Modified by:   100yang
# @Last Modified time: 2020-04-17
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

userprofile/models.py
from django.db import models

# Create your models here.


class userprofile(models.Model):
    # 用户名
    username = models.CharField(max_length=100)
    # 用户邮箱
    email = models.CharField(max_length=100)
    # 用户密码
    password = models.CharField(max_length=100)

userprofile/forms.py
# -*- coding: utf-8 -*-
# @Author: 100yang
# @Date:   2020-04-17
# @Last Modified by:   100yang
# @Last Modified time: 2020-04-17
# 引入表单类
from django import forms
# 引入 User 模型
from django.contrib.auth.models import User

# 登录表单，继承了 forms.Form 类


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()
# 注册用户表单


class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    # 对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")

userprofile/views.py
# from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from .forms import UserLoginForm, UserRegisterForm
# 引入验证登录的装饰器
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# from django.contrib.auth import login, logout


# Create your views here.


def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            if data['username'] == 'admin':
                return redirect("49.232.166.49:8000/admin")
            user = authenticate(
                username=data['username'], password=data['password'])
            if user:
                # 将用户数据保存在 session 中，即实现了登录动作
                login(request, user)
                return redirect("article:ArticleList")
            else:
                return HttpResponse("账号或密码输入有误。请重新输入~")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


# 用户注册
def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        # print('???')
        # print(user_register_form)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return redirect("article:ArticleList")
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {'form': user_register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

# 用户退出


def user_logout(request):
    logout(request)
    return redirect("article:ArticleList")


@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        # 验证登录用户、待删除用户是否相同
        if request.user == user:
            # 退出登录，删除数据并返回博客列表
            logout(request)
            user.delete()
            return redirect("article:article_list")
        else:
            return HttpResponse("你没有删除操作的权限。")
    else:
        return HttpResponse("仅接受post请求。")

templates/userprofile/login.html
{#继承base.html#}
{% extends "base.html" %}
{% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<!-- meta data -->
<meta charset="utf-8">
<!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<!--font-family-->
<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&amp;subset=devanagari,latin-ext" rel="stylesheet">
<!-- title of site -->
<title>Sign in</title>
<!-- For favicon png -->
<link rel="shortcut icon" type="image/icon" href="{% static 'images/favicon.png' % }" />
<!--font-awesome.min.css-->
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<!--animate.css-->
<link rel="stylesheet" href="{% static 'css/animate.css' %}">
<!--bootstrap.min.css-->
<!-- <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css"> -->
<!-- <link rel="stylesheet" href="assets/css/bootstrap.min.css"> -->
<!-- bootsnav -->
<!-- <link rel="stylesheet" href="{% static 'css/bootsnav.css' %}"> -->
<!--style.css-->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!--responsive.css-->
<!-- <link rel="stylesheet" href="{% static 'css/responsive.css' %}"> -->
<!-- <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script> -->
<!-- <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script> -->
<!-- <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script> -->
<!-- <script src="{% static 'js/jquery.js' %}"></script> -->
<!--modernizr.min.js-->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script> -->
<!--bootstrap.min.js-->
<!-- <script src="js/bootstrap.min.js"></script> -->
<!-- bootsnav js -->
<!-- <script src="{% static 'js/bootsnav.js' % }"></script> -->
<!-- jquery.sticky.js -->
<!-- <script src="{% static 'js/jquery.sticky.js' %}"></script> -->
<!--Custom JS-->
<!-- <script src="{% static 'js/custom.js' % }"></script> -->
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
<!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->
<!-- signin end -->
<!-- <form action="." method="post"> -->
<section class="signin popup-in">
    <div class="container">
        <form method="POST" action=".">
            {#            csrf验证#}
            {% csrf_token %}
            <div class="sign-content popup-in-content">
                <div class="popup-in-txt">
                    <h2>sign in</h2>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="signin-form">
                                <div class="form-group">
                                    <label for="username">UserName</label>
                                    <input type="text" class="form-control" id="username" name="username" placeholder="enter your username here">
                                </div>
                                <!--/.form-group -->
                                <div class="form-group">
                                    <label for="password">password</label>
                                    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                                </div>
                                <!--/.form-group -->
                                <!-- </form> -->
                                <!--/form -->
                            </div>
                            <!--/.signin-form -->
                        </div>
                        <!--/.col -->
                    </div>
                    <!--/.row -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="signin-password">
                                <div class="awesome-checkbox-list">
                                    <ul class="unstyled centered">
                                        <li>
                                            <input class="styled-checkbox" id="styled-checkbox-2" type="checkbox" value="value2">
                                            <label for="styled-checkbox-2">remember password</label>
                                        </li>
                                        <li>
                                            <a href="#">Forgot email or password ?</a>
                                        </li>
                                    </ul>
                                </div>
                                <!--/.awesome-checkbox-list -->
                            </div>
                            <!--/.signin-password -->
                        </div>
                        <!--/.col -->
                    </div>
                    <!--/.row -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div>
                                <input type="submit" class="btn signin_btn" value="Sign in">
                                <p>
                                    Don’t have an Account ?
                                    <a href="{% url 'userprofile:register' %}">register</a>
                                </p>
                            </div>
                            <!--/.signin-footer -->
                        </div>
                        <!--/.col-->
                    </div>
                    <!--/.row -->
                </div><!-- .popup-in-txt -->
            </div>
        </form>
        <!--/.sign-content -->
    </div>
    <!--/.container -->
</section>
{% endblock content %}

templates/userprofile/register.html
{% load static %}
{% block title %} 注册 {% endblock title %}
{% block content %}



<!-- Meta tags -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- //Meta tags -->
<link rel="stylesheet" href="{% static 'css/register_style.css' %}" type="text/css" media="all" /><!-- Style-CSS -->
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet"><!-- font-awesome-icons -->
<section class="w3l-form-36">
    <div class="form-36-mian section-gap">
        <div class="wrapper">
            <div class="form-inner-cont">
                <h3>Create your account</h3>
                <form action="#" method="post" class="signin-form">
                    {% csrf_token %}
                    <div class="form-input">
                        <span class="fa fa-user-o" aria-hidden="true"></span>
                        <input type="text" name="username" id="username" placeholder="Username" required />
                    </div>
                    <div class="form-input">
                        <span class="fa fa-envelope-o" aria-hidden="true"></span>
                        <input type="email" name="email" id="email" placeholder="Email" required />
                    </div>
                    <div class="form-input">
                        <span class="fa fa-key" aria-hidden="true"></span>
                        <input type="password" name="password" id="password" placeholder="Password" required />
                    </div>
                    <div class="form-input">
                        <span class="fa fa-key" aria-hidden="true"></span>
                        <input type="password" name="password2" id="password2" placeholder="Confirm Password" required />
                    </div>
                    <div class="login-remember d-grid">
                        <label class="check-remaind">
                            <input type="checkbox">
                            <span class="checkmark"></span>
                            <p class="remember">Remember me</p>
                        </label>
                        <button class="btn theme-button">Signup</button>
                    </div>
                </form>
                <p class="signup">Already a member? <a href="{% url 'userprofile:login' %}" class="signuplink">Login</a></p>
            </div>
        </div>
    </div>
</section>

{% endblock content %}