TourismWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 主页面路由
    path('index/', include('index.urls')),
    # 用户登录注册路由
    path('userprofile/', include('userprofile.urls')),
    # 用户重置密码路由
    path('password-reset/', include('password_reset.urls')),
    # 论坛路由
    path('article/', include('article.urls')),
    # 商城路由
    path('equipMall/', include('equipMall.urls')),
    # 酒店推荐路由
    path("hotel/", include('hotel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # 添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
# -*- coding: utf-8 -*-
# @Author: onezero
# @Date:   2020-03-11
# @Last Modified by:   100yang
# @Last Modified time: 2020-04-25
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('ArticleList/', views.ArticleList, name='ArticleList'),
    path('ArticleDetail/<int:id>/', views.ArticleDetail, name='ArticleDetail'),
    path('ArticleCreate/', views.ArticleCreate, name='ArticleCreate'),
    path('ArticleDelete/<int:id>/', views.ArticleDelete, name='ArticleDelete'),
    path('ArticleUpdate/<int:id>/', views.ArticleUpdate, name='ArticleUpdate'),
    # path()
]

hotel/urls.py
from . import views
from django.urls import path
app_name = 'hotel'

urlpatterns = [
    # 目前还没有urls
]

urlpatterns = [
    # path函数将url映射到视图
    path('hotel-list/', views.hotel_list, name='hotel_list'),
    # 酒店详情
    path('hotel-detail/<int:id>/', views.hotel_detail, name='hotel_detail'),
]

index/urls.py
# 引入views.py
from . import views
from django.urls import path
from django.contrib import admin


app_name = 'index'
urlpatterns = [
    # path函数将url映射到视图
    # 首页路由
    path('index_list', views.index_list, name='index_list'),
    # 管理员首页路由
    path('admin/', admin.site.urls),
]

userprofile/urls.py
# -*- coding: utf-8 -*-
# @Author: 100yang
# @Date:   2020-04-17
# @Last Modified by:   100yang
# @Last Modified time: 2020-04-17
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

templates/base.html
<!-- 载入静态文件 -->
{% load static %}
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="{% static 'layer-v3.1.1/layer/layer.js' %}"></script>
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
</body>

</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">基于Web的旅游信息管理系统</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <a class="navbar-brand nav-link" href="{% url 'index:index_list' %}"　>旅游信息网</a>
        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- Django的 if 模板语句 -->
                {% if user.is_authenticated %}
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href='{% url "userprofile:logout" %}'>退出登录</a>
                        <a class="dropdown-item" href="{%url 'article:ArticleCreate' %}">发布文章</a>
                    </div>
                </li>
                <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:login' %}">登录/注册</a>
                </li>
                <!-- if 语句在这里结束 -->
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="/admin/" target="blank">管理员登录</a>
                </li>
            </ul>
        </div>
    </div>
</nav>