TourismWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 主页面路由
    path('index/', include('index.urls')),
    # 用户登录注册路由
    path('userprofile/', include('userprofile.urls')),
    # 用户重置密码路由
    path('password-reset/', include('password_reset.urls')),
    # 论坛路由
    path('article/', include('article.urls')),
    # 商城路由
    path('equipMall/', include('equipMall.urls')),
    # 酒店推荐路由
    path("hotel/", include('hotel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # 添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
# -*- coding: utf-8 -*-
# @Author: onezero
# @Date:   2020-03-11
# @Last Modified by:   100yang
# @Last Modified time: 2020-04-25
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('ArticleList/', views.ArticleList, name='ArticleList'),
    path('ArticleDetail/<int:id>/', views.ArticleDetail, name='ArticleDetail'),
    path('ArticleCreate/', views.ArticleCreate, name='ArticleCreate'),
    path('ArticleDelete/<int:id>/', views.ArticleDelete, name='ArticleDelete'),
    path('ArticleUpdate/<int:id>/', views.ArticleUpdate, name='ArticleUpdate'),
    # path()
]

hotel/urls.py
from . import views
from django.urls import path
app_name = 'hotel'

urlpatterns = [
    # 目前还没有urls
]

urlpatterns = [
    # path函数将url映射到视图
    path('hotel-list/', views.hotel_list, name='hotel_list'),
    # 酒店详情
    path('hotel-detail/<int:id>/', views.hotel_detail, name='hotel_detail'),
]

index/urls.py
# 引入views.py
from . import views
from django.urls import path
from django.contrib import admin


app_name = 'index'
urlpatterns = [
    # path函数将url映射到视图
    # 首页路由
    path('index_list', views.index_list, name='index_list'),
    # 管理员首页路由
    path('admin/', admin.site.urls),
]

article/models.py
from django.db import models

# Create your models here.

# from django.contrib.auth.models import User

# deal time
from django.utils import timezone

# 博客文章数据模型


# class Category(models.Model):
#     """
#     Django 要求模型必须继承 models.Model 类。
#     Category 只需要一个简单的分类名 name 就可以了。
#     CharField 指定了分类名 name 的数据类型，CharField 是字符型，
#     CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
#     然后给name设置了一个'分类'的名称
#     """
#     name = models.CharField('分类', max_length=100)


# class Tags(models.Model):
#     """
#     标签 Tag 也比较简单，和 Category 一样。
#     再次强调一定要继承 models.Model 类！
#     """
#     name = models.CharField('标签', max_length=100)


class ArticlePost(models.Model):
    author = models.CharField(max_length=10000)
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField('标题', max_length=100)
    body = models.TextField()
    createdtime = models.DateTimeField(default=timezone.now)
    updatetime = models.DateTimeField(auto_now=True)
    # category = models.ForeignKey(
    #     Category, on_delete=models.CASCADE, verbose_name='分类', default='1')
    # tags = models.ManyToManyField(Tags, blank=True)
    # 定义元数据

    class Meta:
        #   ordering 指定模型返回的数据的排列顺序
        #   '-createdtime' 表明数据以倒序排列

        ordering = ('-createdtime',)
    # __str__ 定义当调用对象的 str()　方法时返回值的内容

    def __str__(self):
        return self.title

article/forms.py
# -*- coding: utf-8 -*-
# @Author: onezero
# @Date:   2020-03-11
# @Last Modified by:   onezero
# @Last Modified time: 2020-03-11
from django import forms

# 引入文章模型
from .models import ArticlePost


class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 模型的来源
        model = ArticlePost
        # 定义表单中包含的数据
        fields = ('title', 'body')

article/views.py
# Create your views here.
# from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ArticlePost
from .forms import ArticlePostForm
from django.contrib.auth.models import User
import markdown
from static.spider import quanerCrawl


def getWebArticle():
    # article = ArticlePost.objects.get(id=id)
    article_id = ['7591941', '7591896', '7591810', '7592079',
                  '7591948', '7591946', '7591700', '7591634',
                  '7591546', '7589192', '7588831', '7588449', ]
    for id_1 in article_id:
        html = quanerCrawl.getModule(id_1)
        author = html.getAuthor()
        title = html.getTitle()
        # 判断当前文章是否在数据库中存在
        if ArticlePost.objects.filter(title=title) \
                and ArticlePost.objects.filter(author=author):
            break
        body = html.getContent()
        # now = ArticlePost()  # 当前存储的数据
        new_article = ArticlePost(
            author=author,
            title=title,
            body=body,
        )
        new_article.save()



# 文章列表
def ArticleList(request):
    getWebArticle()
    articles = ArticlePost.objects.all()
    context = {'articles': articles}
    return render(request, 'article/article_list.html', context)



# 文章细节
def ArticleDetail(request, id):
    article = ArticlePost.objects.get(id=id)
    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         # 缩写、表格等常用扩展
                                         'markdown.extensions.extra',
                                         # 语法高亮
                                         'markdown.extensions.codehilite',
                                     ])
    context = {'article': article}
    return render(request, 'article/article_detail.html', context)

# 写文章的视图
def ArticleCreate(request):
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=1)
            new_article.save()
            return redirect("article:ArticleList")
        else:
            return HttpResponse("Error")
    # 用户请求获取数据
    else:
        article_post_form = ArticlePostForm()
        context = {'article_post_form': article_post_form}
        return render(request, 'article/article_create.html', context)

# 删除文章
def ArticleDelete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:ArticleList")
    else:
        return HttpResponse("仅允许POST请求")


# 文章更新
def ArticleUpdate(request, id):
    article = ArticlePost.objects.get(id=id)
    if request.method == 'POST':
        # 将数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            return redirect("article:ArticleDetail", id=id)
        else:
            return HttpResponse("表单有误，请重新填写")
    # 获得数据
    else:
        article_post_form = ArticlePostForm()
        context = {'article': article, 'article_post_form': article_post_form}
        return render(request, 'article/article_update.html', context)


# getWebArticle()

templates/article/article_create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>                
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/article_detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
{{ article.title }}
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 文章详情 -->
<div class="container">
     <div class="breadcrumb">
        <p>您当前所在位置: </p>
        <a class="breadcrumb-item" href="{% url 'index:index_list' %}">Home</a>
        <a class="breadcrumb-item" href="{% url 'article:ArticleList' %}">攻略</a>
        <a class="breadcrumb-item" href="#">{{ article.title }}</a>
    </div>
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <!-- <div class="col-12 alert alert-success">作者：{{ article.author }}</div> -->
        <div class="col-12 alert alert-success">作者：{{ article.author }}
            . <a href="{% url 'article:ArticleUpdate' article.id %}" onclick="Edit">编辑本文</a>
            · <a href="#" onclick="ConfirmDelete()">删除本文</a>
            <!-- {% if user.is_authenticated %} -->
            <!-- 新增一个隐藏表单 -->
            <form style="display: none;" id="Delete" action='{% url "article:ArticleDelete" article.id %}' method="POST">
                {% csrf_token %}
                <button type="submit">发送</button>
            </form>
            <!--              <form style="display: none;" id="Edit" action='{% url "article:ArticleUpdate" article.id %}' method="POST">
                {% csrf_token %}
                <button type="submit">发送</button>
            </form> -->
            <!-- {% endif %} -->
        </div>
        <!-- 文章正文 -->
        <div class="col-12">
            <!-- 加上safe过滤器 不需要转义-->
            {%autoescape off%}
            <p>{{ article.body|safe }}</p>
            {% endautoescape %}
        </div>
    </div>
</div>
<script>
function ConfirmDelete() {
    // body...
    // alert("sss")
    layer.open({
        title: "确认删除",
        content: "是否删除这篇文章",
        yes: function(index, layero) {
            // body...
            $('form#Delete button').click();
            layer.close(index);
            // location.href = '{% url "article:ArticleDelete" article.id %}'
        },
    })
}
</script>
{% endblock content %}

templates/article/article_list.html
<!-- templates/article/list.html -->
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
游记攻略
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="breadcrumb">
        <p>您当前所在位置: </p>
        <a class="breadcrumb-item" href="{% url 'index:index_list' %}">Home</a>
        <a class="breadcrumb-item" href="{% url 'article:ArticleList' %}">攻略</a>
        <!-- <a class="breadcrumb-item" href="#">Data</a> -->
    </div>
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
            <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">
                    {{ article.title }}
                </h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">
                        {% autoescape off %}
                        {{ article.body|slice:'1000' }}...
                        {% endautoescape %}
                    </p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:ArticleDetail' article.id %}" class="btn btn-primary">
                        阅读本文
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}
<!-- -->

templates/article/article_update.html
{% extends "base.html" %} {% load static %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}